llm_type: "OPEN_AI"
temperature: "0"
timeout: "20.0"
search_engine: "serper"
web_browser_engine: "playwright"
PUPPETEER_CONFIG: "./puppeteer-config.json"
MMDC: "/Users/wangli/.npm-global/bin/mmdc"
model_size_threshold : "500 * 1024 * 1024"
PYTORCH_ENABLE_MPS_FALLBACK: "1"
