llm_type: "OPEN_AI"
temperature: "0"
model: "gpt-3.5-turbo-0613"
search_engine: "serper"
web_browser_engine: "playwright"
PUPPETEER_CONFIG: "/Users/wangli/Library/Mobile Documents/com~apple~CloudDocs/历史项目/projects/ddd-gpt/task-ai/puppeteer-config.json"
MMDC: "/Users/wangli/.npm-global/bin/mmdc"