web_browser_engine: "playwright"
PUPPETEER_CONFIG: "./puppeteer-config.q"
MMDC: "/Users/wangli/.npm-global/bin/mmdc"
model_size_threshold : "500 * 1024 * 1024"
PYTORCH_ENABLE_MPS_FALLBACK: "user_1"
state_machine:
  definition : "state_machine_definitions.json"
  context: "state_machine_scenarios.json"


llm:
  base_url: "https://api.openai.com/v1"
  model: "gpt-4o"
  temperature: "0"
  timeout: "20.0"
  rpm: "1"

search:
  api_type: "serpapi"
  api_key: "xxx"

s3:
  access_key: "MOCK_S3_ACCESS_KEY"
  secret_key: "MOCK_S3_SECRET_KEY"
  endpoint: "http://mock:9000"
  secure: false
  bucket: "mock"

azure_tts_subscription_key: "xxx"
azure_tts_region: "eastus"

iflytek_app_id: "xxx"
iflytek_api_key: "xxx"
iflytek_api_secret: "xxx"

thinker_ai_tti_url: "http://mock.com"

repair_llm_output: true