name: thinker-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - fastapi
  - SpeechRecognition
  - pydub
  - pydantic
  - starlette<0.28.0,>=0.27.0
  - pip
  - pip:
    - aim
    - anthropic
    - edge-tts
    - promptlayer
    - edge_tts
    - langchain
    - google-cloud-speech
    - openai
    - tiktoken
    - loguru
    - bs4
    - libcst
    - python-docx
    - scipy
    - llama-cpp-python
    - httplib2
    - pydantic
    - playwright
    - selenium
    - asynctest
    - pyyaml
    - pytest-asyncio
    - injector
    - spade
    - email-validator
    - ipython
    - deepdiff
    - scikit-learn
    - matplotlib
    - plotly
    - pandas
    - kaleido
    - mlxtend