name: thinker-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - fastapi
  - SpeechRecognition
  - pydub
  - pydantic
  - starlette<0.28.0,>=0.27.0
  - transformers
  - datasets>=2.18.0
  - pip
  - pip:
    - aim
    - anthropic
    - edge-tts
    - promptlayer
    - edge_tts
    - langchain
    - langchain-community
    - google-cloud-speech
    - openai
    - tiktoken
    - loguru
    - bs4
    - libcst
    - python-docx
    - scipy
    - llama-cpp-python
    - httplib2
    - pydantic
    - playwright
    - selenium
    - asynctest
    - pyyaml
    - pytest-asyncio
    - injector
    - spade
    - email-validator
    - ipython
    - deepdiff
    - scikit-learn
    - matplotlib
    - plotly
    - pandas
    - kaleido
    - seaborn
    - statsmodels
    - keras
    - tensorflow
    - torch
    - scikit-learn
    - huggingface_hub
    - tf-keras
    - soundfile
    - librosa
    - torchvision
    - gradio
    - gymnasium
    - sentencepiece
    - timm
    - packaging
    - addict
    - editdistance
    - einops
    - fairscale
    - jsonlines
    - markdown2
    - more_itertools
    - nltk
    - numpy
    - opencv_python_headless
    - openpyxl
    - Pillow
    - sacrebleu
    - shortuuid
    - spacy
    - tqdm
    - protobuf
    - typing_extensions
    - uvicorn
    - accelerate
