name: thinker-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - fastapi
  - SpeechRecognition
  - pydub
  - pydantic
  - starlette<0.28.0,>=0.27.0
  - transformers
  - datasets>=2.18.0
  - google-generativeai
  - pip
  - pip:
    - aim
    - anthropic
    - edge-tts
    - promptlayer
    - edge_tts
    - langchain
    - langchain-community
    - google-cloud-speech
    - openai
    - tiktoken
    - loguru
    - bs4
    - libcst
    - python-docx
    - scipy
    - llama-cpp-python
    - httplib2
    - pydantic
    - playwright
    - selenium
    - asynctest
    - pyyaml
    - pytest-asyncio
    - injector
    - email-validator
    - ipython
    - deepdiff
    - scikit-learn
    - matplotlib
    - plotly
    - pandas
    - kaleido
    - seaborn
    - statsmodels
    - tensorflow
    - torch
    - scikit-learn
    - huggingface_hub
    - tf-keras
    - soundfile
    - librosa
    - torchvision
    - gradio
    - gymnasium
    - sentencepiece
    - timm
    - packaging
    - addict
    - editdistance
    - einops
    - fairscale
    - jsonlines
    - markdown2
    - more_itertools
    - nltk
    - numpy
    - opencv_python_headless
    - openpyxl
    - Pillow
    - sacrebleu
    - shortuuid
    - spacy
    - tqdm
    - protobuf
    - typing_extensions
    - uvicorn
    - accelerate
    - bcrypt
    - passlib
    - fastapi-jwt-auth
    - nest-asyncio
    - lightgbm
    - chardet
    - llama-index-embeddings-openai
    - semantic_kernel
    - pyppeteer
    - gitignore_parser
    - nbformat
    - nbconvert
    - paddleocr
    - chromadb
    - llama-index
    - llama-index-vector-stores-postgres
    - llama-index-vector-stores-elasticsearch
    - llama-index-vector-stores-chroma
    - llama-index-retrievers-bm25
    - llama-index-llms-openai
    - lancedb
    - qdrant_client
    - zhipuai
    - dashscope
    - aioredis
    - aioboto3
    - qianfan
    - rank_bm25
    - semantic-kernel==0.4.3.dev0
    - evaluate
    - jieba
    - anytree
    - imap_tools
    - llama-index-embeddings-azure-openai
    - llama-index-embeddings-gemini
    - llama-index-embeddings-ollama
    - llama-index-vector-stores-faiss
    - meilisearch
    - spark_ai_python
    - webdriver_manager
    - azure-cognitiveservices-speech
    - keras
    - annoy
    - curl_cffi
    - pytest-mock
    - ipykernel
    - gitpython
    - pydantic-core < 2.16.0
    - clip
    - rf-groundingdino
    - connexion
    - modelscope
    - pyshine
    - pyarrow
